# Generated by Django 4.0.2 on 2022-03-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
    ]
