# Generated by Django 4.0.2 on 2022-03-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_profile_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_reg',
        ),
    ]
