# Generated by Django 4.0.2 on 2022-03-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_user_profile_user_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_reg',
            new_name='user',
        ),
    ]
